version: "3"

services:
  postgres-data:
    container_name: postgres-data
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_URL: ${POSTGRES_URL}

  auth-api:
    build: ./auth-api
    container_name: auth-api
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_URL: ${POSTGRES_URL}
      X_INTERNAL_TOKEN: ${INTERNAL_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
      DATA_API_URL: "http://data-api:8081"
    depends_on:
      - postgres-data
      - data-api

  data-api:
    build: ./data-api
    container_name: data-api
    ports:
      - "8081:8081"
    environment:
      X_INTERNAL_TOKEN: ${INTERNAL_TOKEN}

